name = "kodoro"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kodoro-db"
database_id = "641e4e89-318b-410a-bd46-4b476fd0e3ed"
